// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDS6zA0SpS87-8L2nuiktuSPowLYlMJvM',
    appId: '1:122093076862:web:be68f932fbe35f0ce2332f',
    messagingSenderId: '122093076862',
    projectId: 'meeting-summariz',
    authDomain: 'meeting-summariz.firebaseapp.com',
    storageBucket: 'meeting-summariz.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDam33IVfF2bInjNOlYCvmltes2M0M4aXY',
    appId: '1:122093076862:android:46ca68e04818b554e2332f',
    messagingSenderId: '122093076862',
    projectId: 'meeting-summariz',
    storageBucket: 'meeting-summariz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUw6I9TAJhJwjPqI4auZ-GsOOTCMjbhTc',
    appId: '1:122093076862:ios:351b23bf777eedf0e2332f',
    messagingSenderId: '122093076862',
    projectId: 'meeting-summariz',
    storageBucket: 'meeting-summariz.firebasestorage.app',
    iosBundleId: 'com.example.meetingSummarizer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUw6I9TAJhJwjPqI4auZ-GsOOTCMjbhTc',
    appId: '1:122093076862:ios:351b23bf777eedf0e2332f',
    messagingSenderId: '122093076862',
    projectId: 'meeting-summariz',
    storageBucket: 'meeting-summariz.firebasestorage.app',
    iosBundleId: 'com.example.meetingSummarizer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDS6zA0SpS87-8L2nuiktuSPowLYlMJvM',
    appId: '1:122093076862:web:b1305af33aaf45f0e2332f',
    messagingSenderId: '122093076862',
    projectId: 'meeting-summariz',
    authDomain: 'meeting-summariz.firebaseapp.com',
    storageBucket: 'meeting-summariz.firebasestorage.app',
  );
}
